import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from '@/components/Navbar'

import './globals.css'
import Sidebar from '@/components/sidebar'
import RegisterModal from '@/components/RegisterModal'
import getCurrentUser from './actions/getCurrentUser'
import ClientOnly from '@/components/ClientOnly'
import InvoiceModal from '@/components/InvoiceModal'
import NextThemeProvider from './providers/ThemeProvider'
import { Toaster } from '@/components/ui/toaster'
import DeleteModal from '@/components/DeleteModal'

const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();


  return (
      <html lang="en">
          <body className={inter.className}>
            <NextThemeProvider>
            <ClientOnly>
            <main className='flex gap-4 w-full'>
              <Sidebar />
              <section className='w-full h-full md:ml-52'>
                <Navbar currentUser={currentUser} />
                <RegisterModal />
                <InvoiceModal />
                {children}
              </section>
              <Toaster />
            </main>
            </ClientOnly>
            </NextThemeProvider>

          </body>

      </html>
  )
}
